### ISSUE TITLE
Pagination for Comic Pages

### ISSUE THREAD

**Issue by SickSick6** [davidjeddy/pieces-compendium-v2#6] opened 2018-01-31 00:06 UTC
Not sure if this is the same as the other Issue ticket named 'Add page number to the bottom of article/view' but I would like to have numbers, or in the least a Beginning & End button added to each page in the comic. This is one example I've seen a couple places:
https://en-support.files.wordpress.com/2013/07/comic-navigation.jpeg
where you have First & Prev buttons on the left side, Next & Latest buttons on the right and a Random button in the middle. I don't think we need the Random button though really as it's a linear plot & doesn't have that many pages.
There's also the generic & language-universal arrow symbols. Like 1 arrow for Next & Previous and 2 overlapping arrows for the First & Latest buttons. 
It would also be good to have the navigation buttons at the bottom as well as the top of the comic page so you don't have to scroll all the way to the bottom.
I would prefer either the First, Previous, Next, Latest format or just arrow icons in the same format. Which ever is easier.

**Comment by davidjeddy** [comment] 2018-01-31 01:03
Duplicate of #3 , please add notes to original issue.

**Closed** 2018-01-31 01:03 UTC
Labels: duplicate
